config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles do
  	resources :comments
  end
  root to: 'articles#index'
  resources :tags

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	def tag_list
 		tags.join(", ")
	end
	
	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags


	end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
    has_many :articles, through: :taggings
	def to_s
    	name
	end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	include ArticlesHelper
	def index
	  @articles = Article.all
	end
	
	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article.id
	end

	def new
		@article = Article.new

	end

	def create
		@article = Article.new(article_params)
  		@article.save
  		redirect_to article_path(@article)

	end

	def destroy
		@a = Article.find(params[:id])
		@a.destroy
		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)
		flash.notice = "Article '#{@article.title}' Updated!"
  		redirect_to article_path(@article)
	end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	include CommentsHelper
	def create
		print comment_params
		@com = Comment.new(comment_params)
		@com.article_id = params[:article_id]

		#print "The stuff is #{comment_params}"
		@com.save

		redirect_to article_path(@com.article)

	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find(params[:id])
	end

	def index
		@tags = Tag.all
	end

	def destroy
		@tag = Tag.find(params[:id])

		@tag.update({articles: []})
		@tag.destroy
		redirect_to tags_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
	  params.require(:article).permit(:title, :body, :tag_list)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>By <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
</p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>
Editor
</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>
<p>
<%= link_to "Create a New Article", new_article_path() %>
</p>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>

<%= link_to "<< Back to Articles List", articles_path %>
<p>
<%= link_to "Edit Article", edit_article_path(@article) %>
<br><br>
<%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"}
 %>
</p>
<h3> Comments
(<%= @article.comments.length%>)
</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<div>
<h4> Add a Comment </h4>
<%= form_for([@article,@comment]) do |f| %>
<p>
    <%= f.label :author_name , "Your name"%><br />
    <%= f.text_field :author_name %>
</p>
<p>
    <%= f.label :body ,"Your comment"%><br />
    <%= f.text_field :body %>
</p>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p>
	<%= f.submit %>
</p>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="flash"><%= flash.notice %></p>

    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1> All Tags </h1>

<ul>
<% @tags.each do |tag| %>

<li> <%= link_to tag.name, tag_path(tag) %> </li>
<% end %>

</ul>
<p> <%= link_to "Back to Articles", articles_path %>

app/views/tags/show.html.erb
<h1> Tag Name <%= @tag.name %> </h1>
<ul>
<% @tag.articles.each do |a| %>
<li>
<%= link_to a.title, article_path(a) %>
</li>
<% end %>
</ul>

<p> <%= link_to "Delete Tag",  tag_path(@tag), method: :delete, data: {confirm: "Really delete the article?"} %> </p>